### PR TITLE
yet another

### PR DESCRIPTION
**Pull request by block-spider**
test @testtip fixes #10 oh

### CODE REVIEW

**Comment by block-spider** [comment]
@testtip @tea-spoon

**Comment by block-spider** [comment]
@testtip @tea-spoon

**Comment by block-spider** [comment]
@testtip @tea-spoon

**Comment by testtip** [comment]
@tea-spoon, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4tyt93upk49l2us9s784ncl2z5guachjy4af) `0.0003 BCH`| `~   0.36 USD` by @block-spider via [chaintip](http://www.chaintip.org).

**Pull request closed without merging**
